A few edits
CBonnell/servercert pull request #5
Opened 2024-04-22 14:59 UTC by CBonnell

2024-04-23 18:13 UTC, slghtr-says commented on docs/BR.md
> +1. Sign the `tbsCertificate` with a "dummy" Private Key whose Public Key component is not certified by a Certificate that does not chain to a publicly-trusted CA Certificate; or
```suggestion
1. Sign the `tbsCertificate` with a "dummy" Private Key whose Public Key component is certified by a Certificate that does not chain to a publicly-trusted CA Certificate; or
```
Removing 'not' to remove the double-negative

2024-04-26 14:56 UTC, CBonnell commented on docs/BR.md
> +1. Sign the `tbsCertificate` with a "dummy" Private Key whose Public Key component is certified by a Certificate that does not chain to a publicly-trusted CA Certificate; or
```suggestion
1. Sign the `tbsCertificate` with a "dummy" Private Key whose Public Key component is not certified by a Certificate that chains to a publicly-trusted CA Certificate; or
```

2024-05-16 10:52 UTC, dzacharo requested changes
Some improvements to the definition of "Linting". I like the new structure of 4.3.1.

2024-05-16 10:52 UTC, dzacharo commented on docs/BR.md
> +**Linting**: A process where the content of a signed document such as a Certificate, Certificate Revocation List, or OCSP response is checked for conformance with the profile defined in these Require
```suggestion
**Linting**: A process where the content of digitally signed data such as a Certificate, Certificate Revocation List, or OCSP response, or data-to-be-signed like a `tbsCertificate` (as described in [section 4.1.1.1 of RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.1.1)) is checked for conformance with the profiles and requirements defined in these Requirements.
```

2024-08-21 13:02 UTC, closed without merging